# Generated by Django 5.0.2 on 2024-02-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_remove_project_tags_image_tag"),
    ]

    operations = [
        migrations.RemoveField(model_name="image", name="image",),
        migrations.AddField(
            model_name="image",
            name="image_url",
            field=models.TextField(default="", max_length=1000),
        ),
    ]
