# Generated by Django 5.0.2 on 2024-02-29 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact", old_name="fullname", new_name="name",
        ),
    ]
