# Generated by Django 5.0.2 on 2024-04-01 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_rename_fullname_contact_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="contact", name="phone",),
    ]
