# Generated by Django 5.0.2 on 2024-04-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0003_remove_contact_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="query",
            field=models.TextField(help_text="Enter your query", max_length=2000),
        ),
    ]
