# Generated by Django 5.0.2 on 2024-02-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=1000)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "tags",
                    models.TextField(
                        blank=True, help_text='Separate tags with ","', max_length=1000
                    ),
                ),
            ],
        ),
    ]
