# Generated by Django 5.0.2 on 2024-03-28 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_remove_image_image_image_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=1000)),
                (
                    "icon",
                    models.CharField(
                        default="assets/images/icon/idea.png", max_length=50
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.service",
            ),
        ),
    ]
