# Generated by Django 5.0.2 on 2024-04-04 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_service_project_service"),
    ]

    operations = [
        migrations.DeleteModel(name="Tag",),
    ]
